# Site settings
title: Custom Parse Emails
email: jgatjens@gmail.com
description: "Custom parse emails for parse.com static templates"
baseurl: "/parse-emails"
# url: "http://yourdomain.com"

# Build settings
markdown: kramdown
# permalink: pretty

exclude: [Gemfile]


apptitle: Pokemon App
password: 
 desc: New Password for
 button: Change Password

verification: Successfully verified your email!
passwordupdate: Successfully updated your password!


